/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include<unistd.h>
#include "bakery.h"


void
bakery_prog_1(char *host, int client_id)
{
	CLIENT *clnt;
	struct BAKERY  *result;
	struct BAKERY  bakery_proc_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, BAKERY_PROG, BAKERY_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	bakery_proc_1_arg.id = client_id;
	bakery_proc_1_arg.number = -1;

	result = bakery_proc_1(&bakery_proc_1_arg, clnt);
	if (result == (struct BAKERY *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Посетитель %d получил номер %d\n", result->id, result->number);
	bakery_proc_1_arg.number = result->number;

	sleep(5);

	result = bakery_proc_1(&bakery_proc_1_arg, clnt);
	if (result == (struct BAKERY *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Посетитель %d получил букву %c\n", result->id, result->letter);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char client_id;

	if (argc < 3) {
		printf ("usage: %s server_host client_id\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	client_id = *(argv[2]) - '0';
	bakery_prog_1 (host, client_id);
exit (0);
}
